### PR TITLE
Add new issue templates for submitting labeled data and ordinary issue

### PR DESCRIPTION
**Pull request by gymgym1212**
There are two new template files users can choose.

#677

### CODE REVIEW

**Comment by gymgym1212** [comment]
https://github.com/gymgym1212/open-digger/issues/new?assignees=&labels=&template=submit_labeled_data.md

**Comment by frank-zsy** [comment]
If we add an issue template, we may need to consider ourselves as normal developers and stand in their position.

So the content of the issue should be from a developer which may contains like `"I want to add some labeled data into OpenDigger to help us for our community analysis"`.

And the information we want developers aware should be annotated like you see here: https://github.com/microsoft/vscode/blob/main/.github/ISSUE_TEMPLATE/bug_report.md?plain=1

**Comment by gymgym1212** [comment]
Yes, this is my problem, and I will fix it as soon as possible.

**Comment by frank-zsy** [comment]
Thx, I think this template is enough for most scenarios.

/approve

**Pull request merged**
