### PR TITLE
fix: fix the file path and throw error if the file not found

### LINKED ISSUE #1400: [Bug] The metrics test has some errors
### Current Behavior

The file path is not right so the test will fall into pass but with correct file path, some of the tests will fail.

### Expected Behavior

With right file path the test should all pass.

### Any Additional Comments?

_No response_

### PR DESCRIPTION
**Pull request by frank-zsy**
fix #1400

Fix the file path and throw error if test data file not found.

### CODE REVIEW

**Comment by frank-zsy** [comment]
@Zzzzzhuzhiwei I did some minor fixes of the test file, and right now most of the tests pass but there are 29 tests fail. Can you give a look on this.

**Comment by Zzzzzhuzhiwei** [comment]
It seems that this part of the data may have some problems, and I will correct it.

**Comment by Zzzzzhuzhiwei** [comment]
hi @frank-zsy, if test data file are not found because the data is random or `Invalide group by label: null`

**Comment by frank-zsy** [comment]
Ok, then we can remove the `throw error` part. After that how many tests fail?

**Pull request closed without merging**
