### PR TITLE
refactor: change the date format for export data

### LINKED ISSUE #1074: [Proposal] discussion of the organized format of the JSON data offered by OpenDigger
Hi @frank-zsy  , we just talk about the format of the JSON data in [DataEase Metting](https://github.com/X-lab2017/open-wonderland/issues/219). We suggest a new data format but not sure whether it is feasible, so could you help us?
For example, [https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/activity.json](https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/activity.json), currently, it's data format like below :
```json
{
"20221": 26.08,
"20222": 17.04,
"20229": 45.73,
"202210": 57.06
}
```
we suggest a new data format: 
```json
[
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-01",
        "value": 26.08
    },
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-02",
        "value": 17.04
    },
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-09",
        "value": 45.73
    },
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-10",
        "value": 57.06
    }
]
```
@tyn1998, If the data format changed, will it have a big impact on the refactoring of hypercrx? @will-ww @xueqidove @xgdyp could you have other suggestions?

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: frank-zsy <syzhao1988@126.com>

Change date format format from `yyyym(m)` to `yyyy-mm`.

close #1074

### CODE REVIEW

**Comment by xgdyp** [comment]
@tyn1998 Will this change affect hypercrx？

**Comment by tyn1998** [comment]
This change will be a breaking change for Hypercrx, it parses date in this way:

https://github.com/hypertrons/hypertrons-crx/blob/26bccf2d53cfa5862f96e21f3a4b67b7b0292ae5/src/utils/data.ts#L4-L8

So `2022-01` will be converted to `2022--01` if this change takes effect. We need to wrap some code in Hypercrx first so the function of Hypercrx will not be broken.

**Comment by frank-zsy** [comment]
> @tyn1998 Will this change affect hypercrx？

Yes, it will but not immediately after the PR merged. Hypercrx need to add some codes that works for both format and change to new format after the upload process done.

**Pull request merged**
