### PR TITLE
refactor: improve python kernel

### PR DESCRIPTION
**Pull request by lhbvvvvv**
The details of this pr is covered in this issuecomment[#148](https://github.com/X-lab2017/open-digger/issues/1265#issuecomment-1668847447).

### CODE REVIEW

**Comment by xgdyp** [comment]
Hi, since this is a breaking change, I'm wondering how to manage different versions of the kernel. So I think we can design a version control rule first.

**Comment by xgdyp** [comment]
I'll review it this week.

**Comment by lhbvvvvv** [comment]
In this file [`python_v2_sample`](https://github.com/lhbvvvvv/open-digger/blob/python_v2_sample/notebook/python_v2_sample.ipynb), we can see a demo.

**Comment by xgdyp** [comment]
LGTM
/approve

**Pull request merged**
