### PR TITLE
label:add code, image and text label data in AI.

### PR DESCRIPTION
**Pull request by Peng99999**
Add code, image and text label data in AI.

### CODE REVIEW

**Comment by xgdyp** [comment]
Hi, thanks for your contribution. May I have a question, how do you get these labels, by algorithms or by reports?

**Comment by Peng99999** [comment]
> Hi, thanks for your contribution. May I have a question, how do you get these labels, by algorithms or by reports?

I obtained these labels from a report titled: "2023 Trends in the Development of AI-Generated Content (AIGC)."

**Comment by xgdyp** [comment]
Got it. Can you post the report link or URL for more information?

**Comment by Peng99999** [comment]
> Got it. Can you post the report link or URL for more information?
[AIGC 发展趋势报告 2023.pdf](https://github.com/X-lab2017/open-digger/files/12534379/AIGC.2023.pdf)

**Comment by xgdyp** [comment]
LGTM 
/approve

**Pull request merged**
