### PR TITLE
feat:add application domain repository data analysis

### PR DESCRIPTION
**Pull request by PureNatural**
1. capitalize the first letter of label names.
2. add application domain repository data analysis.

There is a [issue](https://github.com/X-lab2017/open-digger/issues/1128) with image output

### CODE REVIEW

**Comment by frank-zsy** [comment]
There should be some other errors in your env, all works fine in my local env.
image
Did you use `npm run notebook` to start the notebook? I assume you did, but I can not find out what else may go wrong here.

**Comment by frank-zsy** [comment]
What Node.js version you use? You can run `node -v` to check out, you should use Node.js version at least 14.17

**Comment by frank-zsy** [comment]
I have updated the data in the notebook and rerun all the results to update the data to 2022.12 so they can be used in the report. @PureNatural @xgdyp

**Comment by xgdyp** [comment]
Thanks！

**Comment by PureNatural** [comment]
> There should be some other errors in your env, all works fine in my local env. image Did you use `npm run notebook` to start the notebook? I assume you did, but I can not find out what else may go wrong here.

I found the cause of the problem.

I use _jupyter notebook_ to start the notebook instead of using _npm run notebook_.

When I use _npm run notebook_ to start the notebook, the image can be output.

Much thanks for your help. @frank-zsy

**Pull request merged**
