### PR TITLE
feat: new export method

### LINKED ISSUE #1033: [Feature] New data export method
As mentioned in #1030 , I would like to make a new data export method to export GitHub repo and user data to OSS, so developers can use the data to implement their own applications.

The plan is:
- Consider the huge amount of repos and users on GitHub, we will only export part of the repos and users which are relatively active. The process is:
  - We will export all the data for the repos which have at least 3 developers participated in any month, the amount will be about 2 million right now.
  - Then we will export all the data for the users who were active on above repos and have at least 20 issue/pull related events in all history, also about 2 million right now.
- For all the repos and users, we will export all the metrics implemented in OpenDigger right now with monthly aggregation, users can get quarterly or yearly data by simple calculation.
- Further metrics implemented will be added to export data after the metrics implementation.
- All the metrics will be stored separately into different files, like `activity.json`, `openrank.json`, `issue_resolution_duration.json`, `bus_factor.json` and etc. So developers can easily choose what data they can use.

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: frank-zsy <syzhao1988@126.com>

close #1033 

What I have done in this PR:

- I add a `repo_openrank` and `user_openrank` table in Clickhouse online server to query OpenRank for any repo and user on GitHub for any month.
- Change OpenRank query from Neo4j to Clickhouse.
- Move `activity`, `openrank` and `attention` into `indices` file.
- Remove `hacking_hero` and `hypercrx` related tasks, instead using `monthly_export` task to export all the data to OSS
  - The task will sample repo and user about 2 million each to export
  - The task will export all the metrics and indices implemented in OpenDigger
  - All the metrics and indices will be stored in different files

### CODE REVIEW

**Comment by frank-zsy** [comment]
Other fixes:

- `order` related part has problem for all the metrics, actually in `monthly_export` task, we calculate metrics for lots of repos in the same time and we don't really need to order the results which is quite resource consuming. So handle the situation that `order` is not set.

**Comment by frank-zsy** [comment]
@xgdyp I think this PR is ready for review, can you review and approve this PR.

**Comment by xgdyp** [comment]
OK

**Comment by tyn1998** [comment]
Hi @frank-zsy, as we are developing [this](https://github.com/hypertrons/hypertrons-crx/pull/548) in Hypercrx, @wxharry found an issue that `repo-activity-openrank-trend` of [microsoft/vscode](https://github.com/microsoft/vscode) cannot be correctly displayed in development version, but works well in store version.

The cause is: it seems some of the data files are not updated so they still use the "yyyym(m)" format. The store version works because at the moment it still support the two formats while the development version has removed code that process the old format.

some wrong data links:

- https://oss.x-lab.info/open_digger/github/microsoft/vscode/activity.json
- https://oss.x-lab.info/open_digger/github/microsoft/vscode/openrank.json
- https://oss.x-lab.info/open_digger/github/microsoft/TypeScript/activity.json
- https://oss.x-lab.info/open_digger/github/microsoft/TypeScript/openrank.json

image

Did you regenerate all data files recently? Or the problem may have been existing since last data export.

**Comment by frank-zsy** [comment]
The data process has done. You can check them now.

**Comment by frank-zsy** [comment]
The data process has done. You can check them now.

**Comment by zhicheng-ning** [comment]
> The data process has done. You can check them now.

some data is not updated.
- https://oss.x-lab.info/open_digger/github/jina-ai/docarray/issues_closed.json
- https://oss.x-lab.info/open_digger/github/jina-ai/docarray/bus_factor.json

**Comment by frank-zsy** [comment]
I am overwhelmed by this bug, I will open a new issue to track this one.

**Pull request merged**
