### PR TITLE
Metric：change requests accepted

### PR DESCRIPTION
**Pull request by longyanz**
Hi, I am trying to implement the metric :  change requests accepted #581 .I have implemented the logic and ran local tests.

### CODE REVIEW

**Comment by frank-zsy** [comment]
@longyanz if you ran local test, can you add a demo case into notebook.

**Comment by xiaoya-yaya** [comment]
You can refer to #866, please add demos to notebook/handbook.ipynb and notebook/handbook_zh.ipynb

**Comment by longyanz** [comment]
add demos.

**Comment by frank-zsy** [comment]
In the handbook.ipynb file, I think you add a redundant `2015` in the chart title so the title has 2 `2015`s. You should replace the first `2015` by `${startYear}` and remove the tail `${startYear}`.

**Comment by longyanz** [comment]
Sorry, I have corrected it.

**Comment by xiaoya-yaya** [comment]
LGTM

**Comment by frank-zsy** [comment]
@xiaoya-yaya Next time, you should use `/approve` to merge a pull.

**Pull request merged**
