### PR TITLE
data: add operating system label data

### LINKED ISSUE #1057: [Data] Add data for Operating System label.
I want to add some labeled data into OpenDigger to help us for our community analysis.

The data is from GitHub repo search API with operating system topic and with star greater than 100.

Label: Operating System

Type: Tech-0

Repos:

- torvalds/linux
- SerenityOS/serenity
- redox-os/redox
- s-matyukevich/raspberry-pi-os
- reactos/reactos
- bottlerocket-os/bottlerocket
- NodeOS/NodeOS
- klange/toaruos
- ravynsoft/ravynos
- includeos/IncludeOS
- tock/tock
- oshi/oshi
- nuta/kerla
- armbian/build
- nebulet/nebulet
- archcraft-os/archcraft
- theseus-os/Theseus
- skiftOS/skift
- PureDarwin/PureDarwin
- joshiemoore/snakeware
- FydeOS/chromium_os-raspberry_pi
- haiku/haiku
- vlang/vinix
- Harvey-OS/harvey
- ivandavidov/minimal
- illumos/illumos-gate
- amaneureka/AtomOS
- KnightOS/KnightOS
- AnarchyLinux/installer
- jens-maus/RaspberryMatic
- ffwff/lilith
- hermitcore/rusty-hermit
- unikraft/unikraft
- managarm/managarm
- LemonOSProject/LemonOS
- halfer53/winix
- brutal-org/brutal
- dzavalishin/phantomuserland
- hyperledger/cello
- nieklinnenbank/FreeNOS
- 1j01/98
- hermitcore/libhermit-rs
- Zeal-Operating-System/ZealOS
- Supercip971/WingOS
- nifanfa/MOOS
- PDP-10/its
- xboot/xboot
- adi1090x/CustomArch
- Andy-Python-Programmer/aero
- opuntiaOS-Project/opuntiaOS
- frednora/gramado
- FlingOS/FlingOS
- KilledByAPixel/OS13k
- PowerNex/PowerNex
- klange/ponyos
- WukLab/LegoOS
- thethumbler/Aquila
- pritamzope/OS
- nuta/resea
- DISTORTEC/distortos
- qword-os/qword
- CorruptedByCPU/Cyjon
- MQuy/mos
- ZystemOS/pluto
- Abb1x/emerald
- byteduck/duckOS
- willdurand/ArvernOS
- Antergos/Cnchi
- JehanneOS/jehanne
- MannyPeterson/HeliOS
- RWTH-OS/eduOS-rs
- AndreaOrru/zen
- aros-development-team/AROS
- manticoreos/manticore
- skyzh/core-os-riscv
- flouthoc/wiser
- yourtion/YOS
- mell-o-tron/MellOs
- IsaacWoods/poplar
- hermitcore/libhermit
- ethan4984/rock
- MandelbrotOS/MandelbrotOS
- emutos/emutos
- aura-systems/Aura-Operating-System
- MarcoCicognani/MeetixOS
- StevenBaby/onix

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: frank-zsy <syzhao1988@126.com>

close #1057 

Add repos for operating system label.

I run some tests on my local env, here are some screenshots.

Operating system OpenRank trending by year.

image

Operating system repo OpenRank by year.

image

### CODE REVIEW

**Comment by frank-zsy** [comment]
@xgdyp Can you review and approve this one?

**Comment by xgdyp** [comment]
Hi @frank-zsy , did OS don't have sub-labels(Tech-1)?

**Pull request merged**
