### PR TITLE
labeled data: add oss101 data

### PR DESCRIPTION
**Pull request by Zzzzzhuzhiwei**
Hi, this PR  added ecnu-oss101-2023-spring label data submitted in previous issues.
close https://github.com/X-lab2017/open-digger/issues/1217

### CODE REVIEW

**Comment by xgdyp** [comment]
hi @frank-zsy, can you review this?

**Comment by frank-zsy** [comment]
@Zzzzzhuzhiwei I think you should also change the folder name to `ecnu-oss101-2023-spring` since there may other oss101 class in the future.

**Comment by Zzzzzhuzhiwei** [comment]
> @Zzzzzhuzhiwei I think you should also change the folder name to `ecnu-oss101-2023-spring` since there may other oss101 class in the future.
Okay, I'll modify it now~

**Pull request merged**
