### PR TITLE
docs: fix typo of `user login`

### LINKED ISSUE #1272: [Docs] Typo at `open-digger/README.md`
### Description

https://github.com/X-lab2017/open-digger/blob/b35b78d030ebb644a4029b95fc4e96fd3a7b1b33/README.md?plain=1#L9

According to comment _originally posted by @xgdyp in https://github.com/X-lab2017/open-digger/issues/1256#issuecomment-1510182393_. I suppose I can fix this typo by making changes as below.

```diff
- ... or user `login` to get your data. 
+ ... or `user login` to get your data. 
```

### PR DESCRIPTION
**Pull request by tc2000731**
fixes #1272

### CODE REVIEW

**Comment by xgdyp** [comment]
hi, do you think login name is  better?

**Comment by tc2000731** [comment]
> hi, do you think login name is better?

@xgdyp I think `owner` fits in well since github docs use it in `<owner>/<repo>` pattern.

> The owner and repository name. For example, `octocat/Hello-World`. 
> 
> src: https://docs.github.com/en/actions/learn-github-actions/variables

**Comment by xgdyp** [comment]
> > hi, do you think login name is better?
> 
> @xgdyp I think `owner` fits in well since github docs use it in `<owner>/<repo>` pattern.
> 
> > The owner and repository name. For example, `octocat/Hello-World`.
> > src: https://docs.github.com/en/actions/learn-github-actions/variables

Agree！

**Pull request merged**
