### PR TITLE
refactor: upgrade sample data docker image and dataset

### PR DESCRIPTION
**Pull request by frank-zsy**
Signed-off-by: frank-zsy <syzhao1988@126.com>

related to #1087 

Upgrade sample data ClickHouse server image and sample dataset, includes:

- [x] Upgrade ClickHouse server image to 22.8, use [new docker image](https://hub.docker.com/layers/clickhouse/clickhouse-server/22.8-alpine/images/sha256-415781c84b19c0dca3bd056a34a149b0464be554ab6d1380098c975c45eaabe9?context=explore) to replace the [old one](https://hub.docker.com/layers/yandex/clickhouse-server/20.8/images/sha256-de87befb7948fcda208c348f8572ce26a47abe4ce018253858b6f6d6a3824c2a?context=explore), which introduces a new feature that use a single docker image to support multiple platforms.
  - Remove `Dockerfile_arm` and `build_image_arm.sh` and use `Dockerfile` and `build_image.sh` to build images for amd64 and arm64 platform.
  - As docker image manifest mechanism, we use `docker buildx` to build the image and directly push to registry, if someone wish to build a local image to use, please refer to [this issue](https://github.com/docker/buildx/issues/59#issuecomment-1168619521), use single platform arg and `--load` to build a local image.
  - We use a single image(docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v2) to provide service for multiple platform like below, users can specify the `--platform` on `docker pull` or `docker run` to load the corresponding image.
image

- [x] Update all the dataset, including:
  - [x] corresponding SQL files: change database and table name.
  - [x] OSS static files: compress data and upload to OSS again.

### CODE REVIEW

**Comment by frank-zsy** [comment]
I also need someone with ARM env to test the image.

You should download a sample dataset to test. The smallest one is [`paddle_hackathon_3`]().

Use `docker run -d --name paddle_hackathon_3 -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=$(pwd)/data/paddle_hackathon_3/:/data/ --platform linux/arm64 docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v2` to start the container, should modify the data path to the right place.

Check if the dataset can be successfully loaded into the server and the records count should be `802652`.

**Comment by xgdyp** [comment]
I'll test it.

**Comment by xgdyp** [comment]
image

It's right!

**Comment by frank-zsy** [comment]
OK, I think we are fine, after Python kernel update, the upgrade process for ClickHouse server can be completed.

**Pull request merged**
