### PR TITLE
Feature:add sofastack weekly report

### PR DESCRIPTION
**Pull request by wengzhenjie**
#602 
I just develop a demo for sofastack. However, we also need a timed task component.

### CODE REVIEW

**Comment by seeflood** [comment]
Thanks for your nice help!

**Comment by frank-zsy** [comment]
There is no data for sofa repos in the test docker data image, did you test in local env for this component? @wengzhenjie

**Comment by wengzhenjie** [comment]
> There is no data for sofa repos in the test docker data image, did you test in local env for this component? @wengzhenjie
I just tested it. Here is a real demo.
image

**Comment by frank-zsy** [comment]
Did you test this on `github-sample-log:2.202105`? The CI process returns empty data for the component

**Comment by wengzhenjie** [comment]
> Did you test this on `github-sample-log:2.202105`? The CI process returns empty data for the component

Yeah! There is no result when I test in `github-sample-log:2.202105`.

**Comment by frank-zsy** [comment]
So the result above is based on real data right? So maybe I need to switch CI data set from test data to online data.

**Comment by wengzhenjie** [comment]
> So the result above is based on real data right? So maybe I need to switch CI data set from test data to online data.

Of course！The weekly report is real-time. The data in container may not fit.

**Comment by frank-zsy** [comment]
OK, I will update the CI file first and run this component again for test.

**Comment by frank-zsy** [comment]
@wengzhenjie Please update your PR and rebase the new change in order to test this PR on online data set.

**Comment by frank-zsy** [comment]
I am not sure if I did it right but there is still no data for sofa repos. According to the numbers in global study, the data set has been changed already.

**Comment by frank-zsy** [comment]
Server side will throw `nodejs.Error: Cannot parse date: value is too short: while converting '6/17/2021' to Date (version 20.8.7.15)` error which causes empty data for sofa repos.

@wengzhenjie can you use packages to generate date string explicitly rather than `toLocaleDateString` to make sure the behavior is constant. And time zone should be considered too.

**Comment by frank-zsy** [comment]
Works fine now, thanks.

/approve

**Pull request merged**
