### PR TITLE
data: update database label data (total 206) refer to DB-Engines in Dec, 2022.

### LINKED ISSUE #1093: [Data] Add label data for Database technical area labled on DB-Engines Ranking in Dec, 2022.
I want to add some labeled data into OpenDigger to help us for our community analysis.
The data is based on [DB-Engines](https://db-engines.com/en/ranking) in Dec, 2022. It is an extended version of labeled data submited in https://github.com/X-lab2017/open-digger/issues/1055, which is based on DB-Engines Open Soure DBMS in Nov, 2022.

**Filter conditions**: `Rankings in the DB-Engines Rankings table in Dec, 2022`  and `has repository on GitHub`.  Compared with the dataset submitted before this edit, **the condition `has open source license` is not verified**!

Notes: The DBMS labeled dataset will keep updating at [birdflyi](https://github.com/birdflyi)/[db_engines_ranking_table_crawling](https://github.com/birdflyi/db_engines_ranking_table_crawling). The list below is auto-generated by [wiget_autogen_issue_body_for_opendigger_submiting_labeled_data_issue](https://github.com/birdflyi/wiget_autogen_issue_body_for_opendigger_submiting_labeled_data_issue).

Label: Content

Type: Tech-1

Repos:

- apache/jackrabbit
- ModeShape/modeshape

Label: Document

Type: Tech-1

Repos:

- mysql/mysql-server
- postgres/postgres
- mongodb/mongo
- redis/redis
- elastic/elasticsearch
- MariaDB/server
- databricks/dbt-databricks
- couchbase/couchbase-lite-ios
- apache/impala
- apache/couchdb
- greenplum-db/gpdb
- googleapis/python-firestore
- hazelcast/hazelcast
- marklogic/marklogic-data-hub
- realm/realm-cocoa
- aerospike/aerospike-server
- openlink/virtuoso-opensource
- arangodb/arangodb
- orientechnologies/orientdb
- yugabyte/yugabyte-db
- oracle/nosql-go-sdk
- trinodb/trino
- ravendb/ravendb
- pouchdb/pouchdb
- pingcap/tidb
- rethinkdb/rethinkdb
- citusdata/citus
- apache/drill
- jcrosby/cloudkit
- MonetDB/MonetDB
- apple/foundationdb
- tarantool/tarantool
- beardedeagle/mnesiac
- mbdavid/LiteDB
- oceanbase/oceanbase
- Alachisoft/NCache
- opengauss-mirror/openGauss-server
- bigchaindb/bigchaindb
- crate/crate
- dolthub/dolt
- Postgres-XL/Postgres-XL
- AlaSQL/alasql
- percona/percona-server-mongodb
- techfort/LokiJS
- ydb-platform/ydb
- SequoiaDB/SequoiaDB
- terminusdb/terminusdb
- surrealdb/surrealdb
- Softmotions/ejdb
- ArcadeData/arcadedb
- appy-one/acebase
- xtdb/xtdb
- sachin-sinha/BangDB
- iboxdb/ftserver
- Alachisoft/NosDB
- torodb/server
- DevrexLabs/OrigoDB
- mgholam/RaptorDB-Document
- LinkedInAttic/sensei
- priitj/whitedb
- oberasoftware/jasdb

Label: Event

Type: Tech-1

Repos:

- EventStore/EventStore
- NEventStore/NEventStore

Label: Graph

Type: Tech-1

Repos:

- redis/redis
- MariaDB/server
- neo4j/neo4j
- openlink/virtuoso-opensource
- arangodb/arangodb
- orientechnologies/orientdb
- ravendb/ravendb
- JanusGraph/janusgraph
- dgraph-io/dgraph
- apache/giraph
- vaticle/typedb
- vesoft-inc/nebula
- blazegraph/database
- memgraph/memgraph
- microsoft/GraphEngine
- apache/incubator-hugegraph
- apache/tinkerpop
- twitter-archive/flockdb
- fluree/db
- terminusdb/terminusdb
- surrealdb/surrealdb
- ArcadeData/arcadedb
- hypergraphdb/hypergraphdb
- sachin-sinha/BangDB
- rayokota/hgraphdb
- bitnine-oss/agensgraph
- stellardb/StellarDB

Label: Key-value

Type: Tech-1

Repos:

- redis/redis
- couchbase/couchbase-lite-ios
- memcached/memcached
- hazelcast/hazelcast
- etcd-io/etcd
- aerospike/aerospike-server
- ehcache/ehcache3
- apache/ignite
- arangodb/arangodb
- scylladb/scylla
- basho/riak_kv
- orientechnologies/orientdb
- facebook/rocksdb
- oracle/nosql-go-sdk
- trinodb/trino
- google/leveldb
- infinispan/infinispan
- berkeleydb/libdb
- LMDB/lmdb
- oracle/coherence
- gridgain/gridgain
- apache/geode
- apple/foundationdb
- griddb/griddb
- tarantool/tarantool
- Alachisoft/NCache
- zopefoundation/ZODB
- hibari/hibari
- microsoft/GraphEngine
- etcd-io/bbolt
- jankotek/mapdb
- scalaris-team/scalaris
- Snapchat/KeyDB
- hthetiot/Tokyo-Tyrant
- voldemort/voldemort
- ArcadeData/arcadedb
- speedb-io/speedb
- codenotary/immudb
- AlticeLabsProjects/kyoto
- tomp2p/TomP2P
- ledisdb/ledisdb
- reverbrain/elliptics
- rescrv/HyperLevelDB
- STSSoft/STSdb4
- bytedance/terarkdb
- cruppstahl/upscaledb
- dgraph-io/badger
- dlitz/resin
- simerplaha/SwayDB
- bergdb/bergdb
- cachelot/cachelot
- datajaguar/jaguardb
- estraier/tkrzw

Label: Multivalue

Type: Tech-1

Repos:

- jrmarino/AdaBase
- cran/scidb
- dioptre/rasdaman
- gregjurman/openqm

Label: Native XML

Type: Tech-1

Repos:

- marklogic/marklogic-data-hub
- openlink/virtuoso-opensource
- berkeleydb/libdb
- BaseXdb/basex
- sedna/sedna
- eXist-db/exist

Label: Navigational

Type: Tech-1

Repos:

Label: Object oriented

Type: Tech-1

Repos:

- iboxdb/db4o-gpl
- objectbox/objectbox-java
- The-Alchemist/perst
- zhihu/Matisse
- atoti/atoti
- morecraf/Siaqodb
- DevrexLabs/OrigoDB

Label: RDF

Type: Tech-1

Repos:

- marklogic/marklogic-data-hub
- openlink/virtuoso-opensource
- apache/jena
- blazegraph/database
- eclipse/rdf4j
- 4store/4store
- esarbanis/strabon
- dajobe/librdf
- terminusdb/terminusdb
- njh/redstore
- quoll/mulgara
- dydra/dydra
- BrightstarDB/BrightstarDB

Label: Relational

Type: Tech-1

Repos:

- mysql/mysql-server
- postgres/postgres
- sqlite/sqlite
- twitter-archive/snowflake
- MariaDB/server
- apache/hive
- databricks/dbt-databricks
- postgis/postgis
- FirebirdSQL/firebird
- apache/spark
- apache/impala
- prestodb/presto
- ClickHouse/ClickHouse
- greenplum-db/gpdb
- h2database/h2database
- cockroachdb/cockroach
- KxSystems/kdb
- fosslc/Ingres
- openlink/virtuoso-opensource
- apache/ignite
- apache/derby
- ryenus/hsqldb
- timescale/timescaledb
- yugabyte/yugabyte-db
- oracle/nosql-go-sdk
- trinodb/trino
- pingcap/tidb
- percona/percona-server
- citusdata/citus
- apache/phoenix
- apache/drill
- gridgain/gridgain
- heavyai/heavydb
- MonetDB/MonetDB
- apache/druid
- illarionov/SpatiaLite
- VoltDB/voltdb
- taosdata/TDengine
- apple/foundationdb
- griddb/griddb
- tarantool/tarantool
- questdb/questdb
- duckdb/duckdb
- apache/kylin
- CUBRID/cubrid
- apache/hawq
- vaticle/typedb
- ALTIBASE/altibase
- oceanbase/oceanbase
- sql-js/sql.js
- opengauss-mirror/openGauss-server
- matrixorigin/matrixone
- crate/crate
- splicemachine/spliceengine
- dolthub/dolt
- Postgres-XL/Postgres-XL
- apache/tajo
- apache/trafodion
- AlaSQL/alasql
- apache/doris
- apache/pinot
- ydb-platform/ydb
- bloomberg/comdb2
- SequoiaDB/SequoiaDB
- google/lovefield
- pipelinedb/pipelinedb
- featurebasedb/featurebase
- codenotary/immudb
- biokoda/actordb
- orbisgis/h2gis
- CptTZ/SmallSQL
- bitnine-oss/agensgraph
- CovenantSQL/CovenantSQL
- edgelesssys/edgelessdb

Label: Search engine

Type: Tech-1

Repos:

- mongodb/mongo
- redis/redis
- elastic/elasticsearch
- apache/solr
- opensearch-project/OpenSearch
- marklogic/marklogic-data-hub
- sphinxsearch/sphinx
- openlink/virtuoso-opensource
- arangodb/arangodb
- trinodb/trino
- Alachisoft/NCache
- xapian/xapian
- crate/crate
- meilisearch/meilisearch
- milvus-io/milvus
- strapdata/elassandra
- semi-technologies/weaviate
- typesense/typesense
- qdrant/qdrant
- manticoresoftware/manticoresearch

Label: Spatial DBMS

Type: Tech-1

Repos:

- mysql/mysql-server
- postgres/postgres
- mongodb/mongo
- redis/redis
- elastic/elasticsearch
- MariaDB/server
- apache/solr
- influxdata/influxdb
- postgis/postgis
- couchbase/couchbase-lite-ios
- apache/couchdb
- greenplum-db/gpdb
- h2database/h2database
- aerospike/aerospike-server
- openlink/virtuoso-opensource
- trinodb/trino
- ravendb/ravendb
- rethinkdb/rethinkdb
- heavyai/heavydb
- MonetDB/MonetDB
- illarionov/SpatiaLite
- tarantool/tarantool
- opengauss-mirror/openGauss-server
- geomesa/geomesa-geoserver
- Postgres-XL/Postgres-XL
- sachin-sinha/BangDB
- orbisgis/h2gis

Label: Time Series

Type: Tech-1

Repos:

- mongodb/mongo
- redis/redis
- influxdata/influxdb
- ClickHouse/ClickHouse
- KxSystems/kdb
- graphite-project/graphite-web
- prometheus/prometheus
- timescale/timescaledb
- trinodb/trino
- ravendb/ravendb
- oetiker/rrdtool-1.x
- OpenTSDB/opentsdb
- apache/druid
- taosdata/TDengine
- griddb/griddb
- questdb/questdb
- objectbox/objectbox-java
- crate/crate
- VictoriaMetrics/VictoriaMetrics
- kairosdb/kairosdb
- m3db/m3
- apache/iotdb
- basho-labs/Riak-TS-JDBC-Driver
- ArcadeData/arcadedb
- spotify/heroic
- sachin-sinha/BangDB
- SiriDB/siridb-server
- manticoresoftware/manticoresearch
- hawkular/hawkular-metrics
- rackerlabs/blueflood
- sitewhere/sitewhere
- senx/warp10-platform
- kashirin-alex/swc-db
- OpenNMS/newts
- radicalbit/NSDb

Label: Wide column

Type: Tech-1

Repos:

- apache/cassandra
- apache/hbase
- apache/accumulo
- scylladb/scylla
- yugabyte/yugabyte-db
- trinodb/trino
- oceanbase/oceanbase
- strapdata/elassandra
- kashirin-alex/swc-db

### PR DESCRIPTION
**Pull request by birdflyi**
Fix #1093

data: update database label data (total 206) refer to DB-Engines in Dec, 2022. Filter conditions:  `Rankings in the DB-Engines Rankings table in Dec, 2022` and `has open source license` and `has repository on GitHub`.

### CODE REVIEW

**Comment by frank-zsy** [comment]
I found you remove some repos from the original file, is that because some projects are not in DB-Engine rank list in 2022.12 any more but was in the rank list before?

**Comment by birdflyi** [comment]
There is a problem about muti-model DBMS: they may expand more for each time as ranking tables goes by.

**Comment by frank-zsy** [comment]
I think databases in rank list in past should also be in under the label, we should not remove them from database label since they really are database projects.

**Comment by birdflyi** [comment]
Great, I will keep the databases added into rank list and ignore the commercial license. I still doubt whether to keep all the variable labels for both two versions.

**Comment by frank-zsy** [comment]
What do you mean by `both two versions`, what are the two versions?

**Comment by birdflyi** [comment]
For example: `208728772 # repo:milvus-io/milvus` was labeled as `Database - Multivalue`, while it is labeled as `Database - Search Engine`.  Changing the labels may cause redundancy.

You're right, I should strict on deletion and loose on increase. I will change the dataset filter to a more loose one, only if the dbms has a formal github repo link it will be valid. There is no need to concern about Open Source Licence right here.

**Comment by frank-zsy** [comment]
I think there are two types of change.

- If a project/repo is removed from ranking list, we still need to keep it as it was. It maybe removed just because it is no longer active.
- If a project/repo's sub-type is changed, we can change the label to new type or keep both types. Since label data right now has no time series feature.

**Comment by birdflyi** [comment]
Agree. 
The project/repo may always be update incrementally.
I Noticed that `208728772 # repo:milvus-io/milvus` was labeled as `Database - Multivalue` maybe just by mistakes (see https://github.com/birdflyi/db_engines_ranking_table_crawling/blob/main/data/db_engines_ranking_table_full/ranking_crawling_202211_automerged.csv#L247 ). And I checked other dbms label, all of which remains unchanged, so i believe it is a **low probability** event that a project/repo's sub-type is changed. Change the label to a new type is acceptable, while keep both types may not be a good idea here.

**Review by bifenglin — APPROVED** [review]
have no bugs

**Comment by frank-zsy** [comment]
/approve

LGTM

**Comment by frank-zsy** [comment]
@bifenglin You should not merge the PR directly, OpenDigger community do not work this way. We need a committer using `approve` command to merge a PR.

**Pull request merged**
